### ISSUE TITLE
loginユーザーの名前

### ISSUE THREAD

**Issue by shon-vin** [STUDY-GRP/am-server#3]
ログインしたユーザー名の表示は不要でしょうか？
現在はloginAPIでログインしたユーザー名が取得できないため表示していません。
もともと画面としては表示するかなと思っていましたが、現在はどちらでもいいと思っています。

**Comment by kojima-biz** [comment]
ログインユーザーの名前をログイン時に返す様に変更しました。

**Comment by shon-vin** [comment]
ありがとうございます
